language: node_js
node_js: 
- "12"
jdk:
- oraclejdk8
addons:
    sonarcloud: true
script:
- npm run cover
- sonar scanner -Dsonar.login=$SONAR_TOKEN - Dsonar.organization=jhoniercordoba -Dsonar.proyectKey=lab2ArquiSoft -Dsonar.sources='./app' -X
after_succes:
- npm run coveralls
install:
- 'npm install'